### ISSUE TITLE
Add *.csproj file to ADO.NET Chapter

### ISSUE THREAD

**Issue by askingalot** [nashville-software-school/bangazon-inc#103]
The `DepartmentsAndEmployees.csproj` file is needed since it has the reference to `System.Data.SqlClient`.

I think it makes sense to make the students copy and paste all the code instead of giving them a repo to clone because this is the first time they've done a real project in visual studio...but I'm open to other opinions, of course.

**Comment by stevebrownlee** [comment]
Yes, no need for a boilerplate for this.
