### ISSUE TITLE
Add challenges to Student Exercises part 4

### ISSUE THREAD

**Issue by askingalot** [nashville-software-school/bangazon-inc#105]
Since some students finish all orientation exercises much earlier than others, we should add some challenges to the final exercise that reinforce the lessons from orientation. Students who have completed all other exercises can then work on these challenges.

**Comment by copypastedeveloper** [comment]
I use these.  They keep them busy for a long time, and they're all logic problems.

https://gist.github.com/copypastedeveloper/a340b9d9c9796a90b00fab258b044893

**Comment by askingalot** [comment]
Thanks. These look good as “busy work” that’s actually useful. 

I’d appreciate your feedback on my PR too. I was going for something that would revisit what they’ve learned and also let them build a “real” application.
