### ISSUE TITLE
Update POST in Coffee Controller in ASP.NET Web API Controllers Chpt

### ISSUE THREAD

**Issue by leahhoefling** [nashville-software-school/bangazon-inc#111]
Two edits to make to the Coffee Controller POST:   

1) `return CreatedAtRoute("GetCoffee", new { id = newId }, coffee);` is out of scope and needs to be moved up a few lines.

2) `cmd.Parameters.Add(new SqlParameter("@id", id));` isn't needed in the POST and can be removed.

**Comment by stevebrownlee** [comment]
@leahhoefling I'm working on an integration chapter today. Can you snag this ticket?

**Comment by leahhoefling** [comment]
@stevebrownlee Yes, I will!

**Comment by copypastedeveloper** [comment]
I think this should be closed, based on the merge, so...  i'm just gonna click this button.
