### ISSUE TITLE
Update book 2 chapters to instruct students to use Visual Studio

### ISSUE THREAD

**Issue by askingalot** [nashville-software-school/bangazon-inc#119]
The Book 2 chapters currently instruct students to use `dotnet new webapi`. Change this to instruct them to use visual studio `"File/New Project"

**Comment by copypastedeveloper** [comment]
yaaaas

**Comment by stevebrownlee** [comment]
Y u no like CLI commands?

**Comment by copypastedeveloper** [comment]
I just like the ui.  I'm sure its an old dog new trick situation.  I like that it creates the git repo for me with the appropriate .gitignore and all of that stuff too.  i dunno, maybe the cli does that too.  Just never got into it.  feels like me too from the dotnet team to node

**Comment by askingalot** [comment]
I like the command line, but now that we're doing Visual Studio earlier in the course, I think we should just stick with it instead of going back and forth.

**Comment by stevebrownlee** [comment]
Just FYI, the two are not mutually exclusive. You can create the entire solution and projects via `dotnet` and then launch it in visual studio. 

I'm fine with adding in the UI way, but I will still be showing teams how to use the CLI commands. 

Explain the UI way, but keep the command as an addendum

**Comment by stevebrownlee** [comment]
I've updated chapter 2 with instructions for doing everything with Visual Studio. Further refinements will take future tickets.
