### ISSUE TITLE
Data in Student Exercise Controllers- Part 5 Needs to be Updated

### ISSUE THREAD

**Issue by leahhoefling** [nashville-software-school/bangazon-inc#121]
The JSON representation examples are not correct and need to be updated with correct data. Cohort, Instructor, and Student all need updates to the JSON representation.

**Comment by stevebrownlee** [comment]
@leahhoefling What are the corrections that are needed?

**Comment by leahhoefling** [comment]
@stevebrownlee for the corrections, we wanted to do the following:

- For each Cohort, Instructor, and Student (# 2, 3, & 4) add in Ids to the data
- For # 2 & 3 we need to expand Cohort objects
- On # 4, Students should be an array of objects
- On # 4, Instructors should also be an array of objects since cohorts can have multiple instructors
