### ISSUE TITLE
Remove Dapper from BangazonAPI Boilerplate

### ISSUE THREAD

**Issue by askingalot** [nashville-software-school/bangazon-inc#129]
In the event we wish to use the boilerplate again, it would be nice for it to be change to ADO.NET instead of Dapper.

The boilerplate repo...
https://github.com/nashville-software-school/csharp-bangazonapi-boilerplate

**Comment by stevebrownlee** [comment]
@askingalot I updated the boilerplate project to use ADO.NET code and also included an Xunit testing project with the client provider class, and a testing class with one method for them to build on.

Give it gander.

**Comment by askingalot** [comment]
Aparentlyl I never responded to this. Looks good to me.
