### ISSUE TITLE
Students can't update their BangazonSite DB with migrations (without deleting their DB first)

### ISSUE THREAD

**Issue by MissPeperr** [nashville-software-school/bangazon-inc#150]
Students are given the [boilerplate](https://github.com/nashville-software-school/csharp-bangazon-site-boilerplate) for the BangazonSite sprint. However, students can't actually update their databases with their own migrations unless they completely remove the DB in SSMS and the `Migrations` folder in their project. They run into an error with a FK constraint on the `User` table when they try to run `Update-Database`. I think this is a problem with the `ApplicationDbContext` that's given to the students in the boilerplate.

**Comment by stevebrownlee** [comment]
This was fixed with the following commit on the boilerplate repo:

https://github.com/nashville-software-school/csharp-bangazon-site-boilerplate/commit/79508d66b9ef7aab290810362ddb47e5de76efb4
