### ISSUE TITLE
Review Try and Catch 

### ISSUE THREAD

**Issue by megducharme** [nashville-software-school/bangazon-inc#24]
During orientation, review Try and Catch.

**Comment by stevebrownlee** [comment]
@megducharme This is an old ticket, but still very valid. Let's talk tomorrow about a chapter and an exercise with @askingalot

**Comment by stevebrownlee** [comment]
`Company` class maintains a private `List<Employee>`. Exposes public `AddEmployee()` and `GetEmployee(int index)` methods. Show students how an `IndexOutOfRange` exception is a probable outcome of invoking `GetEmployee()` with an index that doesn't exist.

Then show how to wrap the method call in a `try/catch` block to gracefully handle the exception.

**Comment by askingalot** [comment]
Resolved by #33
