### ISSUE TITLE
Static methods and properties in C#

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/bangazon-inc#39]
1. Create `Utility` class
1. Create static method `DisplayStrings()`
1. Instead of using `foreach` or `ForEach()`, use the `Select()` LINQ method to generate an `IEnumerable<string>` and then send that collection to `DisplayStrings()`

**Comment by askingalot** [comment]
I'll take a swing at this...

**Comment by askingalot** [comment]
resolved by #51
