### ISSUE TITLE
Introduce SSMS at the end of the last Bangazon Sprint

### ISSUE THREAD

**Issue by megducharme** [nashville-software-school/bangazon-inc#50]
SSMS takes up too much time to download and install, and it takes up too much hard drive space. Instead of introducing it at the beginning just to run one query to create the database (and then not use it anymore), introduce it at the end when they have more context and when they have already used the Object Explorer more.

**Comment by stevebrownlee** [comment]
Create some data problems that require students to use some more complex SQL statements to solve. They will only work in SSMS since no coding is involved.

**Comment by copypastedeveloper** [comment]
I generally disagree with this, since professionally they'll likely only be using ssms.  I've never once in my career used the sql stuff in visual studio.

**Comment by copypastedeveloper** [comment]
for reference, we teach only ssms and we install it in the initial setup process.  The VM we use has it preinstalled, and here are the instructions students are given: https://www.notion.so/nathangonzalez/Device-Setup-8d30d444839346a38a8c47b61b3db028

**Comment by stevebrownlee** [comment]
Yes, after students got used to it we realized that this issue is no longer relevant
