### ISSUE TITLE
Add CLI project to Orientation

### ISSUE THREAD

**Issue by askingalot** [nashville-software-school/bangazon-inc#60]
Re-purpose https://github.com/nashville-software-school/csharp-bangazoncli-boilerplate

This should be a 2 - 3 day project.

Learning objectives:
1. C# fundamentals
    1. classes / data types
    1. variables / methods
    1. lists / dictionaries
    1. loops / conditionals
1.  SQL
    1. basic CRUD
    1. more complex JOINs
1. Familiarize students with bangazon business domain

**Comment by copypastedeveloper** [comment]
we have this group project that we use, its before they learn sql, but could easily use sql instead of an in memory collection...

**Comment by askingalot** [comment]
Unless there are any objections, I'm going to close this issue now that we have https://github.com/nashville-software-school/Trestlebridge-Farms

**Comment by stevebrownlee** [comment]
Go for it

**Comment by askingalot** [comment]
Resolved by https://github.com/nashville-software-school/Trestlebridge-Farms
