### ISSUE TITLE
Investigate Azure Data Studio

### ISSUE THREAD

**Issue by stevebrownlee** [nashville-software-school/bangazon-inc#93]
Determine its usage in the community, and have C# instructors download and evaluate its ease of use for instruction.

**Comment by stevebrownlee** [comment]
First thing I came across is that, for OSX users, having `ctrl+F5` is not an ideal key mapping. I had to re-map it to `alt+enter`. That's along the lines of what I would I would expect it to be mapped to by default as a developer.

**Comment by copypastedeveloper** [comment]
also, data studio now supports postgres, so thats cool

**Comment by stevebrownlee** [comment]
Closing this since the main content is in the course now. Further refinements will take future tickets.
